### ISSUE TITLE
a question for the plasticFEM

### ISSUE THREAD

**Issue by GHD7777** [cdkozuch/plasticFEM#1]
Thank you very much for what you shared, and they are very helpful to me as I am learning about plasticity FEM. However, I'm having some difficulty understanding the yield function and the constitutive equation used in your program. Could you describe the example in more detail?

**Comment by cdkozuch** [comment]
The heavy lifting is done by the [returnMap.m](https://github.com/cdkozuch/plasticFEM/blob/main/returnMap.m) function. A good explanation of the physics can be found here: [https://mae.ufl.edu/nkim/egm6352/Chap4.pdf](https://mae.ufl.edu/nkim/egm6352/Chap4.pdf). If you are more interested in the linear algebra, a good explanation of that can be found here: [http://library.utia.cas.cz/separaty/2020/MTR/valdman-0536400.pdf](http://library.utia.cas.cz/separaty/2020/MTR/valdman-0536400.pdf). The two references I included in my README are also great resources.

**Comment by GHD7777** [comment]
Thank you very much for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cdkozuch/plasticFEM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月8日(星期天) 凌晨5:53
***@***.***&gt;;
抄送:&nbsp;"&amp; ***@***.******@***.***&gt;;
主题:&nbsp;Re: [cdkozuch/plasticFEM] a question for the plasticFEM (Issue #1)





 
The heavy lifting is done by the returnMap.m function. A good explanation of the physics can be found here: https://mae.ufl.edu/nkim/egm6352/Chap4.pdf. If you are more interested in the linear algebra, a good explanation of that can be found here: http://library.utia.cas.cz/separaty/2020/MTR/valdman-0536400.pdf. The two references I included in my README are also great resources.
