### ISSUE TITLE
about big voxel, how to calculate

### ISSUE THREAD

**Issue by zrx-explorer** [cdkozuch/plasticFEM#3]
I currently have a 3D voxel file with dimensions 64x64x64, and I would like to process it based on your code. Could you please guide me on how to convert it into a .dat file? I attempted to write one myself, but the result showed excessive memory usage. Thank you for your assistance.

**Comment by cdkozuch** [comment]
This code was not designed for multi-element analysis. In theory, it may be able to handle it, but that was never tested. It was developed purely for demonstration purposes. If you have a larger problem, I suggest using a more mature code, like [Elmer](https://www.elmerfem.org/blog/) or [FEniCS](https://fenicsproject.org/).

**Comment by zrx-explorer** [comment]
> This code was not designed for multi-element analysis. In theory, it may be able to handle it, but that was never tested. It was developed purely for demonstration purposes. If you have a larger problem, I suggest using a more mature code, like [Elmer](https://www.elmerfem.org/blog/) or [FEniCS](https://fenicsproject.org/).

Thanks for your earlier reply!
I was trying to change the boundary conditions of your code: In _runFEM.m_, I change line 57-59
`fixDispDofs = [1 2 3 10 12 13 22 4 7 16 19]; %fixed displacement DoFs
nFixDispDofs = numel(fixDispDofs);
dFixDispVals = [zeros(1,7) du*ones(1,4)]; %fixed displacment increment values`
to
`fixDispDofs = [1 10 13 22 4 7 16 19]; %fixed displacement DoFs
nFixDispDofs = numel(fixDispDofs);
dFixDispVals = [zeros(1,4) du*ones(1,4)]; %fixed displacment increment values`
The command line displays 'Warning: Matrix is close to singular or badly scaled. Results may be inaccurate.RCOND =  1.030001e-16.'
And I still got a reasonable result as before.

Then, I converted the matlab code into python for HPC on our server.
However,  the python code:`spsolve(KT_csr[np.ix_(freeDispDofs - 1, freeDispDofs - 1)], RF[freeDispDofs - 1],use_umfpack=True)`
shows a different result than matlab code `KT(freeDispDofs,freeDispDofs)\RF(freeDispDofs)`, and python code does not converge at time step 82.  
Do you know how to change the Matrix division '\' in matlab into one or some functions in python? or do you have any good way to solve this problem?
If you need, I can provide the python code in next message.
Looking forward to your reply!

**Comment by cdkozuch** [comment]
In only constraining 8 degrees of freedom, you have not fully defined the problem. That is why you are getting a matrix warning. As for the python code, I'm not familiar with those libraries, so I unfortunately cannot help with that.

**Comment by zrx-explorer** [comment]
In this case, for one elements and eight nodes, 11 degrees of freedom are constrained. Could you plz tell me, for x elements and y nodes, which degrees of freedom should be constrained? What is the rule that limit freedom in these kinds of problems?

**Comment by cdkozuch** [comment]
Unfortunately, it depends on the problem. At the end of the day, it comes down to whether you can invert the final matrix. An easy way to confirm if the matrix is invertible is to confirm the determinant is nonzero.

**Comment by zrx-explorer** [comment]
Got it. Thanks for your help.
